### ISSUE TITLE
Duplicate entry 'kds-team.app-gd-user-management-xxx' for key 'PRIMARY'

### ISSUE THREAD

**Issue by yustme** [keboola/developer-portal#298] opened 2019-06-10 09:03 UTC
Duplicitní hodnota pro klíč 
https://keboola.slack.com/archives/C02CGK5CL/p1560052808017000

V papertrailu je k tomu ještě dlouhatánská exception:
https://papertrailapp.com/events?q=e6d9f47f-b5de-470c-b3ec-a3a139629094&focus=1074226515975217157

slack:
https://keboola.slack.com/archives/C02CGK5CL/p1560052808017000

**Comment by yustme** [comment] 2019-06-10 09:04
A asi s tím bude souviset i tohle: https://keboola.slack.com/archives/C02CGK5CL/p1560052248016900
```
"message":"ER_DUP_ENTRY: Duplicate entry 'kds-team.app-gd-user-management-xxx' for key 'PRIMARY'
```

**Comment by odinuv** [comment] 2019-06-14 11:49
duplicate of duplicate duplicate https://github.com/keboola/developer-portal/issues/296

**Closed by odinuv** 2019-06-14 11:49 UTC
